/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: "us-east-1",

  aws_cognito_identity_pool_id:
    "us-east-1:a4f5cb4a-8cbd-41a7-9cd1-452f688c6bb7",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_U1kceR4oE", //"us-east-1_sNZ08Q2YU",
  aws_user_pools_web_client_id: "1oat4l9q6po7c237l07bj1qgso", // "6pptid0ufgds2hv2tqet90o68a",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsExports;
